apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  accessModes:
    - ReadWriteOnce 
  storageClassName: gp2  
  resources:
    requests:
      storage: 2Gi  # Adjust the desired storage size
