apiVersion: apps/v1  
kind: ReplicationController
metadata:
  name: flask-app-replication-controller
spec:
  replicas: 2  
  selector:
    app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: indianspeedster/flask-app:0.0.1
        ports:
        - containerPort: 8200
